/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Clock(props) {
  const { nodes, materials } = useGLTF('/clock.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[12.786, 11.97, 0.013]} rotation={[-1.62, 0, -Math.PI]} scale={4.274}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle016_0003.geometry}
          material={materials.Uhr_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle016_1003.geometry}
          material={materials.Uhr_2_Rand}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle016_2003.geometry}
          material={materials.Sec_Zeiger}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle016_3003.geometry}
          material={materials.min_Zeiger}
          rotation={[-2.277, 0, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle000_0003.geometry}
        material={materials['Uhr_2.001']}
        position={[12.786, 11.97, 0.013]}
        rotation={[-1.62, 0, -Math.PI]}
        scale={4.342}
      />
    </group>
  )
}

useGLTF.preload('/clock.glb')
export default Clock;
