/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function Clock(props) {
  const { nodes, materials } = useGLTF("/clock.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[12.786, 11.97, 0.013]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={4.274}
      >
        <group position={[0, -0.285, 0]}>
          <group rotation={[0.05, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_0001.geometry}
              material={materials.Uhr_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_1001.geometry}
              material={materials.Uhr_2_Rand}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_2001.geometry}
              material={materials.Sec_Zeiger}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_3001.geometry}
              material={materials.min_Zeiger}
              rotation={[1.311, 0, 0]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle000_0001.geometry}
            material={materials["Uhr_2.001"]}
            rotation={[0.05, 0, 0]}
            scale={1.016}
          />
        </group>
        <group position={[0, 0.697, 0]}>
          <group rotation={[0.05, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_0002.geometry}
              material={materials.Uhr_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_1002.geometry}
              material={materials.Uhr_2_Rand}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_2002.geometry}
              material={materials.Sec_Zeiger}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_3002.geometry}
              material={materials.min_Zeiger}
              position={[0.042, 0.037, -0.038]}
              rotation={[0.56, 0, 0]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle000_0002.geometry}
            material={materials["Uhr_2.001"]}
            rotation={[0.05, 0, 0]}
            scale={1.016}
          />
        </group>
        <group position={[0, -1.31, 0]}>
          <group rotation={[0.05, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_0003.geometry}
              material={materials.Uhr_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_1003.geometry}
              material={materials.Uhr_2_Rand}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_2003.geometry}
              material={materials.Sec_Zeiger}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_3003.geometry}
              material={materials.min_Zeiger}
              rotation={[2.409, 0, 0]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle000_0003.geometry}
            material={materials["Uhr_2.001"]}
            rotation={[0.05, 0, 0]}
            scale={1.016}
          />
        </group>
        <group position={[0, 1.722, 0]}>
          <group rotation={[0.05, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_0004.geometry}
              material={materials.Uhr_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_1004.geometry}
              material={materials.Uhr_2_Rand}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_2004.geometry}
              material={materials.Sec_Zeiger}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle016_3004.geometry}
              material={materials.min_Zeiger}
              rotation={[-2.277, 0, 0]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Circle000_0004.geometry}
            material={materials["Uhr_2.001"]}
            rotation={[0.05, 0, 0]}
            scale={1.016}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vinyl_obj.geometry}
        material={nodes.vinyl_obj.material}
        position={[-12.357, 3.042, -11.476]}
        scale={[1.434, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.telephone_obj.geometry}
        material={nodes.telephone_obj.material}
        position={[-8.581, 3.042, -11.476]}
        scale={[1.434, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pc_obj.geometry}
        material={nodes.pc_obj.material}
        position={[2.898, 5.552, -12.541]}
        scale={[1.991, 1.335, 0.357]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.paper_obj.geometry}
        material={nodes.paper_obj.material}
        position={[-0.906, 3.656, -11.259]}
        rotation={[0, 0.215, 0]}
        scale={[0.772, 0.149, 0.997]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.art_obj.geometry}
        material={nodes.art_obj.material}
        position={[10.406, 4.043, -5.754]}
        rotation={[Math.PI / 2, 1.32, -Math.PI / 2]}
        scale={[1.991, 1.335, 0.357]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.canvas_obj.geometry}
        material={nodes.canvas_obj.material}
        position={[10.406, 4.043, 4.2]}
        rotation={[Math.PI / 2, 1.32, -Math.PI / 2]}
        scale={[1.991, 1.335, 0.357]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.key_obj.geometry}
        material={nodes.key_obj.material}
        position={[10.406, 4.043, 14.198]}
        rotation={[Math.PI / 2, 0.82, -Math.PI / 2]}
        scale={[1.991, 1.335, 0.357]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piano_obj.geometry}
        material={nodes.piano_obj.material}
        position={[-14.928, 3.811, 2.992]}
        rotation={[0, -0.128, 0]}
        scale={[0.592, 0.207, 2.783]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[2.994, 5.442, -3.539]}
        rotation={[0.03, 0, 0]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[-12.222, 5.442, -3.539]}
        rotation={[-0.284, 0, 0]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[-8.679, 5.442, -3.539]}
        rotation={[-0.284, 0, 0]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[2.014, 6.162, -5.632]}
        rotation={[-Math.PI / 2, -1.322, -Math.PI / 2]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[2.014, 6.162, 4.089]}
        rotation={[-Math.PI / 2, -1.322, -Math.PI / 2]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[6.518, 6.162, 18.903]}
        rotation={[-0.525, -0.662, -0.342]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[-0.254, 5.442, -7.536]}
        rotation={[-0.48, 0.124, 0.064]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[-8.679, 8.472, 2.839]}
        rotation={[-Math.PI / 2, 0.955, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clocks_obj.geometry}
        material={nodes.clocks_obj.material}
        position={[12.513, 12.029, 0.904]}
        rotation={[Math.PI / 2, 1.52, -Math.PI / 2]}
        scale={[8.787, 2.082, 0.468]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[-13.618, 12.402, 0.94]}
        rotation={[0, -Math.PI / 2, 0]}
      />
    </group>
  );
}

useGLTF.preload("/clock.glb");

export default Clock;
