/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Key(props) {
  const { nodes, materials } = useGLTF("/Key.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[11.34, 2.3, 14.24]}
        rotation={[-Math.PI / 2, 0, 1.72]}
        scale={0.013}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-11.715, 31.257, -7.452]}
            rotation={[1.685, 0.16, 1.701]}
            scale={[1, 1, 1.44]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Box007_Material_#30_0"].geometry}
              material={materials["Material_30.001"]}
              position={[0, 0, -0.347]}
            />
          </group>
          <group
            position={[-10.404, 36.954, -56.011]}
            rotation={[1.685, 0.16, 1.701]}
            scale={[1, 1.379, 0.803]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Cylinder004_Material_#30_0"].geometry}
              material={materials["Material_30.001"]}
              position={[-1.378, 0, -1.621]}
            />
          </group>
          <group
            position={[-14.527, 32.656, -24.501]}
            rotation={[1.685, 0.16, 1.701]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["Line001_Material_#30_0001"].geometry}
              material={materials["Material_30.001"]}
              position={[-9.75, 1.803, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Key.glb");

export default Key;
