/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function MainCamera(props) {
  const { nodes, materials } = useGLTF("/main camera.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        fov={45.895}
        position={[-19.017, 5.442, -6.489]}
        rotation={[0.109, -1.291, 0.105]}
      />
    </group>
  );
}

useGLTF.preload("/main camera.glb");
export default MainCamera;
