/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function MainCamera(props) {
  const { nodes, materials } = useGLTF("/main camera.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[-9.704, 5.442, 18.148]}
        rotation={[0.033, -0.385, 0.012]}
      />
    </group>
  );
}

useGLTF.preload("/main camera.glb");
export default MainCamera;
