/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PC(props) {
  const { nodes, materials } = useGLTF('/pc.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2.959, 5.608, -12.716]} rotation={[Math.PI, 0, Math.PI]} scale={1.884}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen_LCD1_0_1.geometry}
          material={materials.LCD1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen_LCD1_0_2.geometry}
          material={materials.Mouse1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Screen_LCD1_0_3.geometry}
          material={materials.Keyboard1}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/pc.glb')
export default PC;

