/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function PCCamera(props) {
  const { nodes, materials } = useGLTF("/pc camera.glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[2.994, 5.442, -3.539]}
        rotation={[0.03, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/pc camera.glb");
export default PCCamera;
