/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Roof(props) {
  const { nodes, materials } = useGLTF('/roof.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.roof.geometry}
        material={nodes.roof.material}
        position={[-4.853, 16.051, 4.36]}
        rotation={[-Math.PI, 0, 0]}
        scale={[17.68, 8.099, 15.016]}
      />
    </group>
  )
}

useGLTF.preload('/roof.glb')
export default Roof;
