/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PCScreen(props) {
  const { nodes, materials } = useGLTF('/pc screen.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Screen_Screen1_0.geometry}
        material={materials.Screen1}
        position={[2.96, 5.608, -12.622]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={1.884}
      />
    </group>
  )
}

useGLTF.preload('/pc screen.glb')
export default PCScreen;