/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Wall(props) {
  const { nodes, materials } = useGLTF('/wall.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wall.geometry}
        material={nodes.wall.material}
        position={[-4.853, 7.952, 0]}
        scale={[17.68, 8.099, 15.016]}
      />
    </group>
  )
}

useGLTF.preload('/wall.glb')
export default Wall;
